project:
  title: "statreport"
  output-dir: _output

format:
  html:
    toc: true
    number-sections: true
    df-print: paged
  pdf:
    toc: true
    number-sections: true
    pdf-engine: pdflatex

metadata:
  bibliography: references.bib
  link-citations: true