project:
  title: "statreport"
  output-dir: _output

format:
  pdf:
    output-file: statreport          # final tracked artifact _output/statreport.pdf
    pdf-engine: pdflatex
    toc: true
    number-sections: true
    keep-tex: false                  # do not retain .tex
    geometry:
      - margin=1in

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

metadata:
  bibliography: references.bib
  link-citations: true