project:
  title: "statreport"
  output-dir: _output

format:
  pdf:
    pdf-engine: lualatex
    toc: true
    number-sections: true
    geometry:
      - margin=1in
    include-in-header:
      - text: |
          \usepackage{polyglossia}
          \setmainlanguage{mongolian}
          \setotherlanguage{english}
          \usepackage{fontspec}
          \setmainfont{CMU Serif}
          \setsansfont{CMU Sans Serif}
          \setmonofont{CMU Typewriter Text}
          \newfontfamily\cyrillicfont{CMU Serif}
          \newfontfamily\cyrillicfontsf{CMU Sans Serif}
          \newfontfamily\cyrillicfonttt{CMU Typewriter Text}
          \usepackage{ragged2e}
          \RaggedRight
          \setlength{\RaggedRightParindent}{\parindent}
  html:
    toc: true
    lang: mn
    code-fold: true

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

crossref: false

metadata:
  link-citations: true
  lang: mn