project:
  title: "statreport"
  output-dir: _output

format:
  pdf:
    pdf-engine: xelatex
    toc: true
    number-sections: true
    geometry:
      - margin=1in
    mainfont: "Arial"
    sansfont: "Arial"
    monofont: "Arial"
    include-in-header:
      - text: |
          \usepackage{polyglossia}
          \setmainlanguage{mongolian}
          \setotherlanguage{english}
  html:
    toc: true
    lang: mn
    code-fold: true

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

crossref: false

metadata:
  bibliography: references.bib
  link-citations: true
  lang: mn
